
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume
  labels:
    app: seaweedfs
    component: volume
spec:
  clusterIP: None
  ports:
  - port: 9333
    name: seaweedfs
  selector:
    app: seaweedfs
    component: volume
